# -*- coding: utf-8 -*-
"""README marker injection. The engine owns whatever lives between
<!-- ENGINE:KEY:START --> and <!-- ENGINE:KEY:END -->; prose stays untouched.

Each image gets a ?v=<content-hash> cache-bust token, so the README only changes
(and GitHub only re-fetches) when that specific asset's bytes change."""

from __future__ import annotations

import hashlib
import os


def _ver(assets_dir, name, salt=""):
    """Cache-bust token: content hash (busts on any byte change) + a short salt
    suffix (busts at least every cycle, e.g. the 2-day bucket) so refreshed stats
    never get served stale from a sticky image cache."""
    p = os.path.join(assets_dir, name)
    try:
        with open(p, "rb") as f:
            h = hashlib.sha1(f.read()).hexdigest()[:10]
    except OSError:
        h = "0"
    return f"{h}-{salt}" if salt else h


def blocks(raw_base: str, assets_dir: str, salt: str = "") -> dict:
    def img(name, alt, width=None):
        wattr = f' width="{width}"' if width else ""
        return f'<img src="{raw_base}/{name}?v={_ver(assets_dir, name, salt)}" alt="{alt}"{wattr}/>'

    return {
        "HEADER": f'<p align="center">\n  {img("header.svg", "Vadim Khristenko", "100%")}\n</p>',
        "RESEARCH": f'<p align="center">\n  {img("research.svg", "Active research: Aethelgard TQ-1.58", "100%")}\n</p>',
        "BESTGAME": f'<p align="center">\n  {img("bestgame.svg", "Best game", "100%")}\n</p>',
        "GAMES": f'<p align="center">\n  {img("games.svg", "Now playing", "100%")}\n</p>',
        "VIBE": f'<p align="center">\n  {img("vibe.svg", "Current vibe", "100%")}\n</p>',
        "STATS": f'<p align="center">\n  {img("dashboard.svg", "Live telemetry: stats, activity, languages", "100%")}\n</p>',
        "FOOTER": f'<p align="center">\n  {img("footer.svg", "Generated by the VAI Profile Engine", "100%")}\n</p>',
    }


def inject(text: str, key: str, content: str) -> str:
    start = f"<!-- ENGINE:{key}:START -->"
    end = f"<!-- ENGINE:{key}:END -->"
    s, e = text.find(start), text.find(end)
    if s == -1 or e == -1:
        print(f"  ! marker {key} not found")
        return text
    return text[: s + len(start)] + "\n" + content + "\n" + text[e:]
