# -*- coding: utf-8 -*-
"""README marker injection. The engine owns whatever lives between
<!-- ENGINE:KEY:START --> and <!-- ENGINE:KEY:END -->; prose stays untouched."""

from __future__ import annotations


def _img(raw_base, name, version, alt, width=None):
    wattr = f' width="{width}"' if width else ""
    return f'<img src="{raw_base}/{name}?v={version}" alt="{alt}"{wattr}/>'


def blocks(raw_base: str, version: str) -> dict:
    img = lambda *a, **k: _img(raw_base, *a, **k)
    return {
        "HEADER": f'<p align="center">\n  {img("header.svg", version, "Vadim Khristenko", "100%")}\n</p>',
        "RESEARCH": f'<p align="center">\n  {img("research.svg", version, "Active research: Aethelgard TQ-1.58", "100%")}\n</p>',
        "GAMES": f'<p align="center">\n  {img("games.svg", version, "Now playing", "100%")}\n</p>',
        "VIBE": f'<p align="center">\n  {img("vibe.svg", version, "This week\'s vibe", "100%")}\n</p>',
        "STATS": f'<p align="center">\n  {img("dashboard.svg", version, "Live telemetry: stats, activity, languages", "100%")}\n</p>',
        "FOOTER": f'<p align="center">\n  {img("footer.svg", version, "Generated by the VAI Profile Engine", "100%")}\n</p>',
    }


def inject(text: str, key: str, content: str) -> str:
    start = f"<!-- ENGINE:{key}:START -->"
    end = f"<!-- ENGINE:{key}:END -->"
    s, e = text.find(start), text.find(end)
    if s == -1 or e == -1:
        print(f"  ! marker {key} not found")
        return text
    return text[: s + len(start)] + "\n" + content + "\n" + text[e:]
