# -*- coding: utf-8 -*-
"""Footer — the engine signature, styled like a Rust build log, stamped each run."""

from .. import theme as t

ASSET = "footer.svg"


def build(ctx):
    w, h = t.WIDE, 104
    stamp = ctx["stamp"]
    week = ctx["week"]
    year = ctx["year"]
    inner = f"""
    <text x="40" y="30" font-family="{t.MONO}" font-size="13" fill="{t.GREEN}">   Compiling</text>
    <text x="150" y="30" font-family="{t.MONO}" font-size="13" fill="{t.FG}">vai-profile v2.0</text>
    <text x="312" y="30" font-family="{t.MONO}" font-size="13" fill="{t.COMMENT}">(github.com/Vadim-Khristenko)</text>
    <text x="40" y="54" font-family="{t.MONO}" font-size="13" fill="{t.GREEN}" font-weight="700">    Finished</text>
    <text x="152" y="54" font-family="{t.MONO}" font-size="13" fill="{t.FG_DIM}">`profile` [optimized + neon] target(s) — week {week:02d}/{year}</text>
    <text x="40" y="78" font-family="{t.MONO}" font-size="13" fill="{t.CYAN}">     Running</text>
    <text x="140" y="78" font-family="{t.MONO}" font-size="13" fill="{t.FG_DIM}">`readme` → all cards regenerated by the VAI Profile Engine</text>
    <text x="{w-40}" y="78" text-anchor="end" font-family="{t.MONO}" font-size="12" fill="{t.RUST}" filter="url(#glow)">⏱ {t.esc(stamp)}</text>
    <circle cx="{w-44}" cy="28" r="5" fill="{t.GREEN}"><animate attributeName="opacity" values="0.4;1;0.4" dur="2s" repeatCount="indefinite"/></circle>
    """
    return t.card(w, h, "~/.engine/build.log", inner, accent=t.GREEN, badge="self-regenerating")
