//! Footer — the engine signature, styled like a Rust build log, stamped each
//! run. v3 really is a Rust build now.

use crate::run::Ctx;
use crate::svg::esc;
use crate::theme as t;
use crate::theme::{CardSpec, Texture};
use anyhow::Result;

pub fn build(ctx: &Ctx) -> Result<Vec<(String, String)>> {
    let w = t::CARD_W;
    let h = 104;
    let inner = format!(
        r#"
    <text x="40" y="30" font-family="{mono}" font-size="13" fill="{green}">   Compiling</text>
    <text x="150" y="30" font-family="{mono}" font-size="13" fill="{fg}">vai-profile v3.0</text>
    <text x="312" y="30" font-family="{mono}" font-size="13" fill="{muted}">(github · codeberg · git.vai-rice.space)</text>
    <text x="40" y="54" font-family="{mono}" font-size="13" fill="{green}" font-weight="700">    Finished</text>
    <text x="152" y="54" font-family="{mono}" font-size="13" fill="{fgd}">`profile` [optimized + neon] target(s) — week {week:02}/{year}</text>
    <text x="40" y="78" font-family="{mono}" font-size="13" fill="{cyan}">     Running</text>
    <text x="140" y="78" font-family="{mono}" font-size="13" fill="{fgd}">`readme` → all cards regenerated by the VAI Profile Engine</text>
    <text x="{tx}" y="78" text-anchor="end" font-family="{mono}" font-size="12" fill="{rust}" filter="url(#glow)">⏱ {stamp}</text>
    <circle cx="{cx}" cy="28" r="5" fill="{green}"><animate attributeName="opacity" values="1;0.4;1" dur="2s" repeatCount="indefinite"/></circle>
    "#,
        mono = t::MONO,
        green = t::GREEN,
        fg = t::FG,
        fgd = t::FG_DIM,
        muted = t::MUTED,
        cyan = t::CYAN,
        rust = t::RUST,
        week = ctx.week,
        year = ctx.year,
        tx = w - 40,
        cx = w - 44,
        stamp = esc(&ctx.stamp),
    );
    let svg = t::card(
        &CardSpec {
            w,
            h,
            title: "~/.engine/build.log",
            badge: "self-regenerating",
            accent: t::GREEN,
            texture: Texture::Grid,
            alt: "Generated by the VAI Profile Engine (Rust)",
        },
        &inner,
    );
    Ok(vec![("footer.svg".into(), svg)])
}
