//! Footer — the closing "build log" pane: a cargo-style compile transcript on
//! the left, a signed VAI monogram plate on the right, and a status strip with
//! the live forge count and the build stamp. The whole card is the engine's
//! sign-off: everything above it was compiled, not hand-placed.

use crate::run::Ctx;
use crate::svg::{esc, fit_text};
use crate::theme as t;
use crate::theme::{CardSpec, Texture};
use anyhow::Result;

pub fn build(ctx: &Ctx) -> Result<Vec<(String, String)>> {
    let w = t::CARD_W;
    // Inner content reaches baseline 140 below the 42px title bar.
    let h = 192;
    let m = t::MARGIN;
    let forges = ctx.agg.platforms.iter().filter(|p| p.reachable).count();
    let forges_total = ctx.agg.platforms.len();
    let cards = crate::run::CARDS.len();
    let accent = ctx.accent("footer", t::GREEN);

    // Left column: the compile transcript (log verbs right-aligned at x=132).
    let log = format!(
        r#"
    <text x="{lx}" y="32" text-anchor="end" font-family="{mono}" font-size="13" font-weight="700" fill="{green}">Compiling</text>
    <text x="{vx}" y="32" font-family="{mono}" font-size="13" fill="{fg}">vai-profile v3.1</text>
    <text x="{cx}" y="32" font-family="{mono}" font-size="12" fill="{muted}">(rust · tokyo-night · smil)</text>
    <text x="{lx}" y="56" text-anchor="end" font-family="{mono}" font-size="13" font-weight="700" fill="{green}">Finished</text>
    <text x="{vx}" y="56" font-family="{mono}" font-size="13" fill="{fgd}">`release` [optimized + neon] in 1.58s — week {week:02}/{year}</text>
    <text x="{lx}" y="80" text-anchor="end" font-family="{mono}" font-size="13" font-weight="700" fill="{cyan}">Running</text>
    <text x="{vx}" y="80" font-family="{mono}" font-size="13" fill="{fgd}">`readme` → {cards} card modules re-rendered from {forges}/{ft} forges</text>
    <text x="{lx}" y="104" text-anchor="end" font-family="{mono}" font-size="13" font-weight="700" fill="{purple}">Signed</text>
    <text x="{vx}" y="104" font-family="{mono}" font-size="13" fill="{fgd}">Vadim Khristenko · every pixel regenerates itself</text>
    "#,
        mono = t::MONO,
        green = t::GREEN,
        cyan = t::CYAN,
        purple = t::PURPLE,
        fg = t::FG,
        fgd = t::FG_DIM,
        muted = t::MUTED,
        lx = m + 108,
        vx = m + 120,
        cx = m + 262,
        week = ctx.week,
        year = ctx.year,
        ft = forges_total,
    );

    // Right column: the monogram plate — a compact signature seal.
    let px = (w - 226) as f64; // plate x
    let plate = format!(
        r#"
    <rect x="{px:.0}" y="20" width="202" height="88" rx="12" fill="{bgd}" stroke="{accent}" stroke-width="1.2" opacity="0.95"/>
    <rect x="{px:.0}" y="20" width="202" height="88" rx="12" fill="none" stroke="{accent}" stroke-width="1.2" opacity="0.35" filter="url(#softglow)"/>
    <text x="{mx:.0}" y="58" text-anchor="middle" font-family="{mono}" font-size="30" font-weight="800" fill="{rust}" filter="url(#glow)">VAI</text>
    <text x="{mx:.0}" y="78" text-anchor="middle" font-family="{mono}" font-size="10.5" fill="{muted}" letter-spacing="2">PROFILE ENGINE</text>
    <text x="{mx:.0}" y="96" text-anchor="middle" font-family="{mono}" font-size="10.5" fill="{fgd}">vai-rice.space</text>
    <circle cx="{dx:.0}" cy="34" r="3.5" fill="{green}"><animate attributeName="opacity" values="1;0.35;1" dur="2.2s" repeatCount="indefinite"/></circle>
    "#,
        bgd = t::BG_DARK,
        rust = t::RUST,
        green = t::GREEN,
        muted = t::MUTED,
        fgd = t::FG_DIM,
        mono = t::MONO,
        mx = px + 101.0,
        dx = px + 186.0,
    );

    // Status strip along the bottom: hairline + stamp.
    let stamp = fit_text(&format!("⏱ last build {}", ctx.stamp), 320.0, 12.0, true);
    let strip = format!(
        r#"
    <line x1="{m}" y1="118" x2="{x2}" y2="118" stroke="{bghl}" stroke-width="1"/>
    <rect x="{m}" y="118" width="200" height="1.6" fill="url(#accentbar)"/>
    <text x="{m}" y="140" font-family="{mono}" font-size="11.5" fill="{muted}">© {year} Vadim Khristenko — hand-written engine, self-written README</text>
    <text x="{x2}" y="140" text-anchor="end" font-family="{mono}" font-size="12" fill="{rust}" filter="url(#glow)">{stamp}</text>
    "#,
        mono = t::MONO,
        bghl = t::BG_HL,
        muted = t::MUTED,
        rust = t::RUST,
        x2 = w - m,
        year = ctx.year,
        stamp = esc(&stamp),
    );

    let svg = t::card(
        &CardSpec {
            w,
            h,
            title: "~/.engine/build.log",
            badge: "self-regenerating",
            accent: &accent,
            texture: Texture::Grid,
            alt: "Build log: this profile is regenerated by the VAI Profile Engine (Rust)",
        },
        &format!("{log}{plate}{strip}"),
    );
    Ok(vec![("footer.svg".into(), svg)])
}
