//! README marker injection. The engine owns whatever lives between
//! `<!-- ENGINE:KEY:START -->` and `<!-- ENGINE:KEY:END -->`; prose stays
//! untouched.
//!
//! Each image gets a `?v=<content-hash>` cache-bust token, so the README only
//! changes (and GitHub only re-fetches) when that specific asset's bytes
//! change; a short salt suffix additionally busts every 2-day cycle so
//! refreshed stats never get served stale from a sticky image cache.

use sha1::{Digest, Sha1};
use std::path::Path;

/// Cache-bust token: 10-hex content hash + optional salt suffix.
pub fn ver(assets_dir: &Path, name: &str, salt: &str) -> String {
    let h = match std::fs::read(assets_dir.join(name)) {
        Ok(bytes) => {
            let mut hasher = Sha1::new();
            hasher.update(&bytes);
            let digest = hasher.finalize();
            digest.iter().take(5).map(|b| format!("{b:02x}")).collect::<String>()
        }
        Err(_) => "0".to_string(),
    };
    if salt.is_empty() {
        h
    } else {
        format!("{h}-{salt}")
    }
}

fn img(raw_base: &str, assets_dir: &Path, name: &str, alt: &str, salt: &str) -> String {
    format!(
        r#"<img src="{raw_base}/{name}?v={}" alt="{alt}" width="100%"/>"#,
        ver(assets_dir, name, salt)
    )
}

fn block(raw_base: &str, assets_dir: &Path, salt: &str, images: &[(&str, &str)]) -> String {
    let rows: Vec<String> = images
        .iter()
        .map(|(name, alt)| format!("  {}", img(raw_base, assets_dir, name, alt, salt)))
        .collect();
    format!("<p align=\"center\">\n{}\n</p>", rows.join("\n"))
}

/// All engine-owned README blocks. `platform_assets` is the ordered list of
/// platform-card file names actually rendered (combined card first).
pub fn blocks(
    raw_base: &str,
    assets_dir: &Path,
    salt: &str,
    platform_assets: &[String],
) -> Vec<(String, String)> {
    let b = |images: &[(&str, &str)]| block(raw_base, assets_dir, salt, images);
    let mut out = vec![
        ("HEADER".to_string(), b(&[("header.svg", "Vadim Khristenko")])),
        (
            "RESEARCH".to_string(),
            b(&[("research.svg", "Active research: Aethelgard TQ-1.58")]),
        ),
        (
            "FLAGSHIP".to_string(),
            b(&[("flagship.svg", "Flagship projects with live stats")]),
        ),
        (
            "LEARNING".to_string(),
            b(&[("learning.svg", "Now learning and building")]),
        ),
        ("BESTGAME".to_string(), b(&[("bestgame.svg", "Best game")])),
        ("GAMES".to_string(), b(&[("games.svg", "Now playing")])),
        ("VIBE".to_string(), b(&[("vibe.svg", "Current vibe")])),
        (
            "STATS".to_string(),
            b(&[("dashboard.svg", "Live telemetry: stats, activity, languages")]),
        ),
        (
            "FOOTER".to_string(),
            b(&[("footer.svg", "Generated by the VAI Profile Engine")]),
        ),
    ];
    let platform_images: Vec<(String, String)> = platform_assets
        .iter()
        .map(|name| {
            let alt = if name.contains("all") {
                "All platforms combined".to_string()
            } else {
                format!(
                    "Platform stats: {}",
                    name.trim_start_matches("platform_").trim_end_matches(".svg")
                )
            };
            (name.clone(), alt)
        })
        .collect();
    let refs: Vec<(&str, &str)> = platform_images
        .iter()
        .map(|(n, a)| (n.as_str(), a.as_str()))
        .collect();
    out.push(("PLATFORMS".to_string(), b(&refs)));
    out
}

/// Replace the engine-owned region for `key`; prose outside markers is never
/// touched. Missing markers are reported and skipped.
pub fn inject(text: &str, key: &str, content: &str) -> String {
    let start = format!("<!-- ENGINE:{key}:START -->");
    let end = format!("<!-- ENGINE:{key}:END -->");
    let (Some(s), Some(e)) = (text.find(&start), text.find(&end)) else {
        crate::log::warn(&format!("marker {key} not found"));
        return text.to_string();
    };
    format!("{}\n{}\n{}", &text[..s + start.len()], content, &text[e..])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn inject_replaces_only_between_markers() {
        let text = "prose\n<!-- ENGINE:X:START -->\nold\n<!-- ENGINE:X:END -->\nmore prose";
        let out = inject(text, "X", "new");
        assert_eq!(
            out,
            "prose\n<!-- ENGINE:X:START -->\nnew\n<!-- ENGINE:X:END -->\nmore prose"
        );
    }

    #[test]
    fn inject_is_idempotent() {
        let text = "a\n<!-- ENGINE:K:START -->\nz\n<!-- ENGINE:K:END -->\nb";
        let once = inject(text, "K", "content");
        let twice = inject(&once, "K", "content");
        assert_eq!(once, twice);
    }

    #[test]
    fn inject_missing_marker_leaves_text_untouched() {
        let text = "no markers here";
        assert_eq!(inject(text, "NOPE", "x"), text);
    }

    #[test]
    fn ver_hashes_content_and_salt() {
        let dir = std::env::temp_dir().join("vai_ver_test");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("a.svg"), b"hello").unwrap();
        let v1 = ver(&dir, "a.svg", "");
        let v2 = ver(&dir, "a.svg", "");
        assert_eq!(v1, v2);
        assert_eq!(v1.len(), 10);
        // sha1("hello") = aaf4c61ddc… → first 10 hex chars
        assert_eq!(v1, "aaf4c61ddc");
        assert_eq!(ver(&dir, "a.svg", "123"), "aaf4c61ddc-123");
        std::fs::write(dir.join("a.svg"), b"changed").unwrap();
        assert_ne!(ver(&dir, "a.svg", ""), v1);
        // Missing file → sentinel, still deterministic.
        assert_eq!(ver(&dir, "missing.svg", "s"), "0-s");
    }
}
